version: "3.9"
services:
  mariadb:
    container_name: mariadb
    image: "mariadb:11.0.2"
    env_file:
      - main.env
  gosling:
    container_name: gosling
    build: .
    restart: always
    depends_on:
      - mariadb
    env_file:
      - main.env