version: "3.9"
services:
  mariadb-host:
    image: "mariadb:10.7"
    env_file:
      - main.env
    volumes:
      - /db:/var/lib/mysql
  gosling:
    build: .
    restart: always
    depends_on:
      - mariadb-host
    env_file:
      - main.env